services:
  # Your Node.js automation server
  automation-server:
    build: .
    container_name: automation-server
    ports:
      - "3000:3000"
    volumes:
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - HEADLESS=false
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - CHROMIUM_WS_ENDPOINT=ws://chromium-browser:9222
      - DISPLAY=:99
    depends_on:
      - chromium-browser
    restart: unless-stopped
    networks:
      - automation-network

  # Visual Chrome container with VNC access
  chromium-browser:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium-browser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=abc
      # Disable dbus to fix the errors
      - NO_DECOR=1
      - DBUS_SESSION_BUS_ADDRESS=""
      # Proper Chrome CLI arguments for debugging
      - CHROME_CLI=--no-sandbox --start-maximized --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - chromium-config:/config
    #ports:
    #   - "4100:3000" # noVNC web interface - VISUAL BROWSER HERE!
    #   - "4101:3001" # VNC port (optional)
    shm_size: "2gb"
    restart: unless-stopped
    networks:
      - automation-network

  # Proxy to make Chrome debugging port accessible from other containers
  # chrome-proxy:
  #   image: alpine/socat
  #   container_name: chrome-proxy
  #   command: TCP-LISTEN:9223,fork,reuseaddr TCP:127.0.0.1:9222
  #   network_mode: "container:chromium-browser"
  #   depends_on:
  #     - chromium-browser
  #   restart: unless-stopped

  # Nginx Proxy Manager
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx-data:/data
      - ./nginx-letsencrypt:/etc/letsencrypt
    networks:
      - automation-network

networks:
  automation-network:
    driver: bridge

volumes:
  chromium-config:
