name: Deploy TopUpAgent Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests (if any)
      run: npm test
      continue-on-error: false
    
    - name: Lint code
      run: npm run lint --if-present

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/topupagent-server:latest
          ghcr.io/${{ github.repository_owner }}/topupagent-server:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Deploy to Hostinger Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Navigate to project directory
          cd ~/TopUpAgentServer
          
          # Pull latest changes
          git pull origin main
          
          # Stop existing containers
          docker-compose down
          
          # Login to GitHub Container Registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Pull latest image
          docker pull ghcr.io/${{ github.repository_owner }}/topupagent-server:latest
          
          # Update docker-compose to use the new image
          sed -i 's|image:.*|image: ghcr.io/${{ github.repository_owner }}/topupagent-server:latest|' docker-compose.yml
          
          # Start services with new image
          docker-compose up -d
          
          # Clean up old images
          docker image prune -f
          
          # Show running containers
          docker ps
          
          # Show logs for verification
          docker-compose logs --tail=50