name: Deploy Theme to Hostinger via SFTP

on:
  push:
    branches:
      - main # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }} # Use the SSH private key from GitHub secrets

      - name: Deploy change file
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.FTP_HOST }} # Your server IP
          remote-user: ${{ secrets.FTP_USER }} # Your SSH username
          private-ssh-key: ${{ secrets.SSH_KEY }} # The private key used for SSH authentication
          ssh-port: ${{ secrets.FTP_PORT }} # Custom SSH port
          source-path: ./src # The local directory to upload
          destination-path: /root/TopUpAgentServer/src # Remote path on the server

      - name: Deploy package.json
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.FTP_HOST }} # Your server IP
          remote-user: ${{ secrets.FTP_USER }} # Your SSH username
          private-ssh-key: ${{ secrets.SSH_KEY }} # The private key used for SSH authentication
          ssh-port: ${{ secrets.FTP_PORT }} # Custom SSH port
          source-path: package.json # The local directory to upload
          destination-path: /root/TopUpAgentServer/package.json # Remote path on the server

      - name: Deploy package-lock.json
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.FTP_HOST }} # Your server IP
          remote-user: ${{ secrets.FTP_USER }} # Your SSH username
          private-ssh-key: ${{ secrets.SSH_KEY }} # The private key used for SSH authentication
          ssh-port: ${{ secrets.FTP_PORT }} # Custom SSH port
          source-path: package-lock.json # The local directory to upload
          destination-path: /root/TopUpAgentServer/package-lock.json # Remote path on the server

      - name: Restart PM2 app
        run: |
          ssh -p ${{ secrets.FTP_PORT }} ${{ secrets.FTP_USER }}@${{ secrets.FTP_HOST }} "pm2 restart app"

      - name: npm install
        run: |
          ssh -p ${{ secrets.FTP_PORT }} ${{ secrets.FTP_USER }}@${{ secrets.FTP_HOST }} "cd /root/TopUpAgentServer && npm install"
